### ISSUE TITLE
Bug: Models not located in coordinates (0,0,0)

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/3D-DFG-Viewer#14]
* [ ]  @thedworak Fix Issue: Models not located in coordinates (0,0,0) - not displayed in the viewer at all or only in part
* [ ]  @thedworak Fix Issue: Models not located in coordinates (0,0,0) - Models lie below the ground level
![Screenshot below](https://user-images.githubusercontent.com/110522037/183454076-b7651e3b-9415-4444-b9cb-e62cd919bf53.png)

* [ ]  @thedworak Fix Issue: Models not located in coordinates (0,0,0) - Some parts of models below ground level
![Screenshot below some parts](https://user-images.githubusercontent.com/110522037/183454099-e3dea7d2-7912-4f92-be10-9e12d33094e4.png)

**Comment by thedworak** [comment]
In fact, their pivot is located in the origin of the axes.

**Comment by ClemensBeck** [comment]
Possible way to solve to the bug via Bounding Box:  https://stackoverflow.com/questions/15492857/any-way-to-get-a-bounding-box-from-a-three-js-object3d

**Comment by thedworak** [comment]
![image](https://user-images.githubusercontent.com/96061043/186396304-c290adf7-893f-41b4-8007-b70a72e69840.png)
![image](https://user-images.githubusercontent.com/96061043/186396352-b61d31e1-b9f0-48c2-8191-cf22d2d42975.png)
![image](https://user-images.githubusercontent.com/96061043/186396402-33b46c81-a4ec-465b-85f8-30b6628974ba.png)
![image](https://user-images.githubusercontent.com/96061043/186396444-2d61eeb8-556b-4501-8285-896cbe53a12e.png)
partly solved, need more feedback after this changes. If something is not placed correctly there are two options:
- metadata has different position (saved by user)
- pivot is not placed correctly

**Comment by ClemensBeck** [comment]
@thedworak How have you partially solved the problem now?

**Comment by thedworak** [comment]
I calculate bounding box and place them in the middle of the distance as (max-min)/2 for x and z axes and in the min for y axis.
