### ISSUE TITLE
Test: UX Interface 

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/3D-DFG-Viewer#15]
* [x] (Constantin Kleiner) UX Interface Test

**Comment by thedworak** [comment]
Rebuilt layout last week completly.

**Comment by ClemensBeck** [comment]
Constantin started just thiw week with the UX test, so he can test the new layout

**Comment by CKFSU** [comment]
Hi, 

attached to this comment you find my UX test and some Screenshots. 

It is in german I hope that works for you? If not I will translate it.

I hope the table I created is self-explaining, If not please feel free to ask.

Best
Constantin

[3D Repository Test.xlsx](https://github.com/thedworak/3D-DFG-Viewer/files/9433628/3D.Repository.Test.xlsx)
![Downloadzeichen und Sharezeichen zu nah im Fullscreenmodus Fullscreenmodus](https://user-images.githubusercontent.com/112182069/186917914-92b31804-aeda-4d01-babc-85e715131483.png)
![Downloadzeichen und Sharezeichen zu nah im Fullscreenmodus Normaler Modus](https://user-images.githubusercontent.com/112182069/186917920-6b3d4a0f-2938-440d-9cf6-a62f5eb1dbe4.png)
![Gesamte Seite lässt sich nach links verschieben (Stichprobenartig getestet) Normal](https://user-images.githubusercontent.com/112182069/186917923-f8bc40a8-2989-4ab6-bad1-7ae65db4e389.png)
![Gesamte Seite lässt sich nach links verschieben (Stichprobenartig getestet) Verschoben](https://user-images.githubusercontent.com/112182069/186917925-ec14b741-8a8a-4c4a-8f73-96819dca8331.png)
![nach Beendigung des Fullscreens ist Position der Kontrollleiste ideal Nach Fullscreen](https://user-images.githubusercontent.com/112182069/186917927-4d147fd2-719e-4512-9d32-ce60454f9dea.png)
![nach Beendigung des Fullscreens ist Position der Kontrollleiste ideal Vor Fullscreen](https://user-images.githubusercontent.com/112182069/186917930-259dab7e-cbdd-4f17-8502-d8ea7406990b.png)

**Comment by CKFSU** [comment]
Hi again,

attached to this comment you find the same documents as above, this time in english. 

If some of my translations failed, just let me know. 

Also my "coding system" is explained in the headline of each column, e.g. "Control bar on the right (0=position ideal; 1=position not ideal)".

If you have any questions please feel free to ask.

Best
Constantin
[3D Repository Test_english.xlsx](https://github.com/thedworak/3D-DFG-Viewer/files/9442687/3D.Repository.Test_english.xlsx)
![After quitting full screen, position of control bar is ideal_after quitting full screen mode](https://user-images.githubusercontent.com/112182069/187152791-466e5057-b238-48e0-aad3-2a70857a6306.png)
![After quitting full screen, position of control bar is ideal_before full screen mode](https://user-images.githubusercontent.com/112182069/187152795-dc73c1d8-32e9-41b0-abb9-22fdef7e95b7.png)
![Download button and share button too close in full screen mode_full screen mode](https://user-images.githubusercontent.com/112182069/187152799-45fece97-068c-46e6-b14b-ae439cfb1037.png)
![Download button and share button too close in full screen mode_normal mode](https://user-images.githubusercontent.com/112182069/187152802-66334d84-ad82-4eaa-9b6c-2d8e7af2628e.png)
![Entire page can be moved to the left (randomly tested)_moved](https://user-images.githubusercontent.com/112182069/187152803-2718cafc-93d3-4208-9e16-5c881fa69631.png)
![Entire page can be moved to the left (randomly tested)_normal](https://user-images.githubusercontent.com/112182069/187152806-7b19f2aa-e7aa-4bd2-9f90-d9714e163a0d.png)

**Comment by CKFSU** [comment]
Hi again again, 

I randomly tested some models again, always some for each browser and all the ones that didn’t load in the first place. For some reason they still don’t work (see the newest column on the right in the excel sheet). Maybe it’s because of my mac or browser versions. 

As Clemens asked me to, here are the informations:

- Software: macOS Monterey 12.1
- Browser Versions:
      Chrome: 105.0.5195.52 (downloaded today)
      Edge: 105.0.1343.25 (downloaded today)
      Firefox: 91.13.0esr (64-Bit)
      Opera: 90.0.4480.80 (x86_64)
      Safari: 15.2 (17612.3.6.1.6)
- Mac Book Air 13’’ (2015), Resolution (default setting): 1440 x 900 

I hope that helps. Let me know if not.

Best 
Constantin

[3D Repository Test_english_20220902.xlsx](https://github.com/thedworak/3D-DFG-Viewer/files/9476271/3D.Repository.Test_english_20220902.xlsx)
