### ISSUE TITLE
Bug: 3D Viewer doesn't display anymore in Firefox browser

### ISSUE THREAD

**Issue by igorbajena** [thedworak/3D-DFG-Viewer#21]
Viewer is not visible at all for any entity in Firefox browser (105.0.3, Firefox Release October 7, 2022). Also automatic renders are dispalyed in the old style (when you slide the mouse over them, they enlarge)
![obraz](https://user-images.githubusercontent.com/109960112/195332078-b2c36661-5bbf-4f0e-b3e1-711c3f1f9c33.png)
![obraz](https://user-images.githubusercontent.com/109960112/195332483-3a9180d5-c3cb-4ce5-a5ee-f511a098f1bb.png)

**Comment by thedworak** [comment]
![image](https://user-images.githubusercontent.com/96061043/195342364-76b75610-ae8d-4304-b92c-8142d80321e9.png)
Known issue on Firefox, not solvable by me. I upgraded the three.js library to newest stable version last week. Have to wait for bugfix from Mozilla.
I tried to make workaround but then Drupal won't serve the content.

**Comment by thedworak** [comment]
Prepared some fix, should work since few days.
