### ISSUE TITLE
Feature: Automatic screenshot (in Progress) 

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/3D-DFG-Viewer#6]
* [ ] @thedworak Automatic screenshot as a preview when the render is not supported

Daniel is doing research until 10th August 2022

**Comment by ClemensBeck** [comment]
Not quite possible right now, rendering has to be done manually. Option to develop it, but will take some time (but also clicking would be necessary), estimation: hart to estimate (up to two weeks)
Discuss with Sander and Piotr if necessary

**Comment by ClemensBeck** [comment]
Possible solution for the feature: https://stackoverflow.com/questions/26193702/three-js-how-can-i-make-a-2d-snapshot-of-a-scene-as-a-jpg-image

**Comment by thedworak** [comment]
Occurs only for non-supported formats (3D clouds). Can be done by hand, by screenshot as well, priority below 0.
