### ISSUE TITLE
Feature: Measurement of Models

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/3D-DFG-Viewer#8]
* [ ] @thedworak Measurement of the models (Scaling/measurement points)

Daniel is doing research until 10th August 2022

**Comment by ClemensBeck** [comment]
* Pretty hard to find anything about it, no plugin available
* problem of the scaling 
* Time-Consuming (every format using different algorithms), more adjustments needed 
* If we need this feature, we should decide which formats we need for it 
* Conclussion: Discuss it with Piotr and Sander

**Comment by ClemensBeck** [comment]
@thedworak added some measurement. Open problems to be addressed are above all the changeability of the unit of measurement

**Comment by thedworak** [comment]
Ruler renamed to Distance Measurement
